Repository mailcow/mailcow-dockerized, pull requests merged in 2023-07, with the labels that each got.

#5215 [web] logger pdo exception handling workaround
  data/web/inc/functions.inc.php
Labels: stale

#5295 Spamhaus DNSBL AS Detection
  .gitignore
  data/Dockerfiles/postfix/Dockerfile
  data/Dockerfiles/postfix/postfix.sh
  data/conf/postfix/main.cf
  docker-compose.yml
  generate_config.sh
  update.sh
Labels: needs testing

#5336 Automatic PR to nightly from 2023-07-28T16:11:41Z
  data/Dockerfiles/postfix/Dockerfile
  data/Dockerfiles/postfix/postfix.sh
  generate_config.sh
  update.sh
Labels: upstream
