Repository mailcow/mailcow-dockerized, pull requests merged in 2024-08, with the labels that each got.

#5661 rspamd: upgrade to rspamd 3.9.1
  data/Dockerfiles/rspamd/Dockerfile
  data/Dockerfiles/rspamd/docker-entrypoint.sh
  data/conf/rspamd/local.d/rbl.conf
  data/conf/rspamd/local.d/rbl_group.conf
  docker-compose.yml
Labels: upstream

#5981 Automatic PR to nightly from 2024-08-05T15:47:31Z
  data/Dockerfiles/acme/Dockerfile
  data/Dockerfiles/acme/acme.sh
  data/Dockerfiles/acme/reload-configurations.sh
  data/Dockerfiles/clamd/Dockerfile
  data/Dockerfiles/dockerapi/Dockerfile
  data/Dockerfiles/dovecot/Dockerfile
  data/Dockerfiles/dovecot/docker-entrypoint.sh
  data/Dockerfiles/dovecot/rspamd-pipe-ham
  data/Dockerfiles/dovecot/rspamd-pipe-spam
  data/Dockerfiles/dovecot/sa-rules.sh
  data/Dockerfiles/netfilter/Dockerfile
  data/Dockerfiles/olefy/Dockerfile
  data/Dockerfiles/phpfpm/Dockerfile
  data/Dockerfiles/phpfpm/docker-entrypoint.sh
  data/Dockerfiles/postfix/Dockerfile
  data/Dockerfiles/rspamd/Dockerfile
  data/Dockerfiles/rspamd/docker-entrypoint.sh
  data/Dockerfiles/sogo/Dockerfile
  data/Dockerfiles/unbound/Dockerfile
  data/Dockerfiles/watchdog/Dockerfile
  data/Dockerfiles/watchdog/watchdog.sh
  data/conf/dovecot/dovecot.folders.conf
  data/conf/rspamd/local.d/rbl.conf
  data/conf/rspamd/local.d/rbl_group.conf
  data/web/autoconfig.php
  data/web/inc/lib/sieve/extensions/enotify.xml
  data/web/inc/lib/sieve/extensions/mime.xml
  data/web/lang/lang.nb-no.json
  docker-compose.yml
  generate_config.sh
  update.sh
Labels: upstream

#5776 Filter to limit ofelia scope
  docker-compose.yml
Labels: investigating

#5992 Automatic PR to nightly from 2024-08-07T07:05:27Z
  data/Dockerfiles/watchdog/watchdog.sh
  data/web/lang/lang.si-si.json
  docker-compose.yml
Labels: upstream

#5996 Automatic PR to nightly from 2024-08-08T06:45:44Z
  data/Dockerfiles/sogo/Dockerfile
  data/Dockerfiles/sogo/syslog-ng-redis_slave.conf
  data/Dockerfiles/sogo/syslog-ng.conf
  data/Dockerfiles/unbound/Dockerfile
  data/Dockerfiles/unbound/healthcheck.sh
  data/Dockerfiles/unbound/stop-supervisor.sh
  data/Dockerfiles/unbound/supervisord.conf
  data/Dockerfiles/unbound/syslog-ng.conf
  data/conf/rspamd/local.d/statistic.conf
  data/web/inc/functions.mailbox.inc.php
  data/web/lang/lang.ru-ru.json
  data/web/lang/lang.uk-ua.json
  docker-compose.yml
  helper-scripts/backup_and_restore.sh
Labels: upstream

#6005 Automatic PR to nightly from 2024-08-13T10:44:24Z
  .github/ISSUE_TEMPLATE/pr_to_nighty_template.yml
  data/Dockerfiles/dovecot/Dockerfile
  data/Dockerfiles/dovecot/docker-entrypoint.sh
Labels: upstream

#6008 Automatic PR to nightly from 2024-08-15T07:42:17Z
  data/web/autoconfig.php
Labels: upstream

#6010 Automatic PR to nightly from 2024-08-15T07:51:57Z
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  data/assets/templates/pw_reset_html.tpl
  data/assets/templates/pw_reset_text.tpl
  data/web/admin.php
  data/web/inc/functions.inc.php
  data/web/inc/functions.mailbox.inc.php
  data/web/inc/init_db.inc.php
  data/web/inc/triggers.inc.php
  data/web/inc/vars.inc.php
  data/web/js/site/mailbox.js
  data/web/json_api.php
  data/web/lang/lang.de-de.json
  data/web/lang/lang.en-gb.json
  data/web/reset-password.php
  data/web/templates/admin.twig
  data/web/templates/admin/tab-config-password-policy.twig
  data/web/templates/admin/tab-config-password-settings.twig
  data/web/templates/edit/mailbox-templates.twig
  data/web/templates/edit/mailbox.twig
  data/web/templates/index.twig
  data/web/templates/modals/mailbox.twig
  data/web/templates/modals/user.twig
  data/web/templates/reset-password.twig
  data/web/templates/user/tab-user-auth.twig
Labels: upstream

#6017 Automatic PR to nightly from 2024-08-16T08:39:08Z
  data/Dockerfiles/acme/acme.sh
  data/Dockerfiles/dockerapi/Dockerfile
  data/Dockerfiles/dovecot/docker-entrypoint.sh
  data/Dockerfiles/dovecot/sa-rules.sh
  data/Dockerfiles/phpfpm/docker-entrypoint.sh
  data/Dockerfiles/postfix/Dockerfile
  data/Dockerfiles/postfix/postfix.sh
  data/Dockerfiles/sogo/Dockerfile
  data/Dockerfiles/sogo/bootstrap-sogo.sh
  data/Dockerfiles/unbound/Dockerfile
  data/Dockerfiles/watchdog/Dockerfile
  data/Dockerfiles/watchdog/watchdog.sh
  docker-compose.yml
  update.sh
Labels: upstream

#6031 Pushover/Quarantine utf 8 fix - fixes #6028
  data/conf/rspamd/meta_exporter/pipe.php
  data/conf/rspamd/meta_exporter/pushover.php
Labels: confirmed

#6027 Automatic PR to nightly from 2024-08-19T12:28:50Z
  data/conf/rspamd/meta_exporter/pipe.php
  data/conf/rspamd/meta_exporter/pushover.php
  generate_config.sh
  update.sh
Labels: upstream

#6035 Automatic PR to nightly from 2024-08-20T11:44:56Z
  update.sh
Labels: upstream
